### ISSUE TITLE
cargo-outdated fails to compile after updating rust toolchain

### ISSUE THREAD

**Issue by ilyapopov** [kbknapp/cargo-outdated#323]
After updating rust toolchain today to 1.62.0, when running

    cargo install --force cargo-outdated

I get this:

```
error[E0599]: no method named `iter` found for opaque type `impl Iterator<Item = &OsString>` in the current scope
  --> /home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.61.1/src/cargo/core/compiler/build_plan.rs:81:35
   |
81 |         for arg in cmd.get_args().iter() {
   |                                   ^^^^ method not found in `impl Iterator<Item = &OsString>`

error[E0599]: no method named `iter` found for opaque type `impl Iterator<Item = &OsString>` in the current scope
   --> /home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.61.1/src/cargo/core/compiler/mod.rs:751:24
    |
751 |     rustdoc.get_args().iter().any(|flag| {
    |                        ^^^^ method not found in `impl Iterator<Item = &OsString>`

error[E0599]: no method named `hash` found for opaque type `impl Iterator<Item = &OsString>` in the current scope
   --> /home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-0.61.1/src/cargo/util/rustc.rs:354:20
    |
354 |     cmd.get_args().hash(&mut hasher);
    |                    ^^^^ method not found in `impl Iterator<Item = &OsString>`

For more information about this error, try `rustc --explain E0599`.
```

    cargo 1.62.0 (a748cf5a3 2022-06-08)
    rustc 1.62.0 (a8314ef7d 2022-06-27)

**Comment by steffahn** [comment]
See https://github.com/rust-lang/cargo/issues/10803

**Comment by ilyapopov** [comment]
Confirm, works now.
